branch-defaults:
  default:
    environment: ctrl-f-be-drf-dev
global:
  application_name: ctrl-f-be-drf
  branch: null
  default_ec2_keyname: thkwon
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
