branch-defaults:
  main:
    environment: ctrlf-backend-prod
    group_suffix: null
  staging:
    environment: testdeploy-dev
environment-defaults:
  testdeploy-dev:
    branch: null
    repository: null
global:
  application_name: testdeploy
  branch: null
  default_ec2_keyname: thkwon
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
